
name: Integration Workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Packages
        run: yarn install

      - name: Check for linting issues
        run: yarn run lint

      - name: Build dist
        run: yarn run dev:build

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Set up SSH Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_IP}}
          username: ${{secrets.USERNAME}}
          passphrase: ${{secrets.PASSWORD}}
          key: ${{secrets.SERVER_SSH_KEY}}
          port: ${{secrets.PORT}}
          script: |
            set -e
            echo "Changing directory to /www/wwwroot/APIs/euapi"
            cd /www/wwwroot/APIS/euapi || {echo "Failed to change directory"; exit 1;}
            echo "Pulling Latest code from origin/main"
            git pull origin main || { echo "Failed to pull latest code"; exit 1; }
            echo "Installing dependencies"
            yarn install || {echo "Failed to install dependencies"; exit 1;}
            echo "Stopping Server To rebuilt"
            yarn run docker:stop || {echo "Couldn't Stop Docker containers"; exit 1;}
            echo "Building Development Files"
            yarn run docker:build || {echo "Failed to build development server"; exit 1;}
            echo "Running deployment"
            yarn run docker:run || {echo "Failed to start server"; exit 1;}
            echo "Deployment successful"


          
